# Generated by Django 3.1.7 on 2021-04-11 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Likers',
            field=models.ManyToManyField(related_name='Favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
